PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS places_new (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  external_id TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  brand_name TEXT,
  branch_name TEXT,
  description TEXT,
  description_source TEXT,
  address TEXT,
  latitude REAL,
  longitude REAL,
  opening_hours_text TEXT,
  opening_hours_json TEXT,
  phone TEXT,
  yandex_rating REAL,
  yandex_reviews_count INTEGER,
  yandex_maps_url TEXT,
  rating_source TEXT,
  rating_updated_at TEXT,
  geocode_provider TEXT,
  geocode_query TEXT,
  geocode_status TEXT,
  geocode_display_name TEXT,
  geocoded_at TEXT,
  source TEXT,
  source_url TEXT,
  fetched_at TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ((latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)),
  CHECK (latitude IS NULL OR (latitude >= -90 AND latitude <= 90)),
  CHECK (longitude IS NULL OR (longitude >= -180 AND longitude <= 180)),
  CHECK (latitude IS NULL OR geocode_status IS NOT NULL),
  CHECK (yandex_rating IS NULL OR rating_source IS NOT NULL)
);

INSERT INTO places_new (
  id,
  external_id,
  display_name,
  brand_name,
  branch_name,
  description,
  description_source,
  address,
  latitude,
  longitude,
  opening_hours_text,
  opening_hours_json,
  phone,
  yandex_rating,
  yandex_reviews_count,
  yandex_maps_url,
  rating_source,
  rating_updated_at,
  geocode_provider,
  geocode_query,
  geocode_status,
  geocode_display_name,
  geocoded_at,
  source,
  source_url,
  fetched_at,
  is_active,
  created_at,
  updated_at
)
SELECT
  id,
  external_id,
  display_name,
  brand_name,
  branch_name,
  description,
  description_source,
  address,
  latitude,
  longitude,
  opening_hours_text,
  opening_hours_json,
  phone,
  yandex_rating,
  yandex_reviews_count,
  yandex_maps_url,
  rating_source,
  rating_updated_at,
  geocode_provider,
  geocode_query,
  geocode_status,
  geocode_display_name,
  geocoded_at,
  source,
  source_url,
  fetched_at,
  is_active,
  created_at,
  updated_at
FROM places;

DROP TABLE places;
ALTER TABLE places_new RENAME TO places;

CREATE INDEX IF NOT EXISTS idx_places_lat_lon ON places(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_places_active ON places(is_active);
CREATE INDEX IF NOT EXISTS idx_places_brand_name ON places(brand_name);
